### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by matthewfeickert** [duetosymmetry/ads2inspire#1]
Hi @duetosymmetry. I'll try to make a PR this week that makes `ads2inspire` a fully `pip` installable package. I noticed that you use an import that indicates that you want to have Python 2 support

https://github.com/duetosymmetry/ads2inspire/blob/bee0003dbf1b7d20246192e5ef57e429766a1a79/ads2inspire.py#L31-L34

Is this needed for you personally? If no, then I'd advocate for dropping Python 2 support entirely and then just moving on with modern Python packaging design, which is intentionally incompatible with Python 2.

**Comment by duetosymmetry** [comment]
Fair point, acceptable to me
