### ISSUE TITLE
Add PyPI and TestPyPI API tokens 

### ISSUE THREAD

**Issue by matthewfeickert** [duetosymmetry/ads2inspire#3]
It would be nice to be able to use GitHub Actions's CI systems to cut releases and distribute to PyPI on version tags and to TestPyPI on pushes to `master`. To do this, a [PyPI API token](https://pypi.org/help/#apitoken) needs to get registered for the project and then added as secrets to the GitHub repo, which can only be done by someone with owner privileges. This was done successfully in [pyhf PR 638](https://github.com/scikit-hep/pyhf/pull/638), for example.

**Comment by duetosymmetry** [comment]
I hope to get to this tomorrow

**Comment by matthewfeickert** [comment]
> I hope to get to this tomorrow

No rush on this. :) This is more just "things that if done help automate away the boring stuff that also presents the most room for mistakes".

**Comment by duetosymmetry** [comment]
I am confused about how version number is determined in this automated approach. Is it based on git tags? Does `setup.cfg` matter? I've tested building locally with `python -m pep517.build --source --binary --out-dir dist/ .` and it seems to ignore `setup.cfg`, seems to care about git tags, and seems to always product `*dev*` versions. Clearly I'm missing some magic, and the docs for pep517 are not helping...

**Comment by matthewfeickert** [comment]
Ah, yeah sorry. I can give a much better answer later today but the short answer is that what is happening is unreleated to PEP 517 (that's just the top lines of `pyproject.toml`) and is due to the choice of `setuptools_scm` and  `setuptools_scm_git_archive`. I didn't explain the workflow properly in my haste that we use for `pyhf`, as it is a bit confusing at first, but the idea is that your package version is in lock step with the Git tags. with `scm_git` each commit after a tag is treated as a dev version of the _next_ tag, which makes it possible to automatically publish to TestPyPI (otherwise you get conflicts). I can give a full example later today.

Also, this workflow is setup to favor automation, and it isn't necessarily "typical", so once I explain it if it doesn't sound fun then we can drop it.

**Comment by duetosymmetry** [comment]
I was looking at the wrong piece of the machine! Thanks, done.
