### ISSUE TITLE
Start using bumpversion

### ISSUE THREAD

**Issue by duetosymmetry** [duetosymmetry/ads2inspire#6]
Instead of manually updating versions and tags, use [bumpversion](https://pypi.org/project/bumpversion/). [Example configuration here](https://github.com/scikit-hep/pyhf/blob/ab533ca5a9f1fd7252ab8c88357872e7f9dee9f5/.bumpversion.cfg#).

**Comment by matthewfeickert** [comment]
I should eventually get around to adding CI (really just porting from another project) that can take care of most of this for a cleaner PR based workflow, but yes, using `bumpversion` is a great way to go no matter what the workflow is.
